"use client";
import { useActionState, useMemo, useState } from "react";
import { formatMilli, formatPKR, multiplyQuantityRate, quantityToMilli } from "@/lib/money";
import { postDeliveries, type DeliveryState } from "./actions";

type Product={sku:string;name:string;unit:string;ratePaisa:string};
type Customer={id:string;code:string;name:string;address:string;normalQuantity:string;ratePaisa:string;paused:boolean};
type Line=Customer&{deliveryStatus:"delivered"|"changed"|"extra"|"skipped"|"paused";milkQuantity:string;notes:string;products:Record<string,string>};
const wasDelivered=(status:Line["deliveryStatus"])=>status!=="skipped"&&status!=="paused";

export function DeliverySheet({customers,products,today}:{customers:Customer[];products:Product[];today:string}){
  const [state,action,pending]=useActionState(postDeliveries,{} as DeliveryState);
  const [businessDate,setBusinessDate]=useState(today);
  const [key]=useState(()=>crypto.randomUUID());
  const [reviewing,setReviewing]=useState(false);
  const [lines,setLines]=useState<Line[]>(()=>customers.map(customer=>({...customer,deliveryStatus:customer.paused?"paused":"delivered",milkQuantity:customer.normalQuantity,notes:"",products:Object.fromEntries(products.map(product=>[product.sku,""]))})));
  const totals=useMemo(()=>lines.reduce((total,line)=>{if(!wasDelivered(line.deliveryStatus))return total;let milk=0n,amount=0n;try{milk=quantityToMilli(line.milkQuantity||"0");amount=multiplyQuantityRate(milk,BigInt(line.ratePaisa));for(const product of products){const value=line.products[product.sku];if(value)amount+=multiplyQuantityRate(quantityToMilli(value),BigInt(product.ratePaisa))}}catch{}return{milk:total.milk+milk,amount:total.amount+amount,delivered:total.delivered+1,skipped:total.skipped}}, {milk:0n,amount:0n,delivered:0,skipped:lines.filter(line=>!wasDelivered(line.deliveryStatus)).length}),[lines,products]);
  const update=(index:number,change:Partial<Line>)=>setLines(current=>current.map((line,i)=>i===index?{...line,...change}:line));
  const payload=JSON.stringify({businessDate,idempotencyKey:key,lines:lines.map(line=>({customerId:line.id,deliveryStatus:line.deliveryStatus,milkQuantity:line.milkQuantity,notes:line.notes,products:products.map(product=>({sku:product.sku,quantity:line.products[product.sku]||""}))}))});
  return <form action={action} className="card table-card delivery-sheet"><input type="hidden" name="payload" value={payload}/>
    <div className="delivery-heading"><div className="field"><label>Delivery date</label><input type="date" value={businessDate} onChange={event=>setBusinessDate(event.target.value)}/></div><div><b>{customers.length} household customers</b><div className="subtitle">Normal quantities are already filled. Change exceptions only.</div></div></div>
    {state.error?<div className="form-error" role="alert">{state.error}</div>:null}
    {state.result?<div className="form-success delivery-receipt"><b>Posted {state.result.transactionNo}</b><span>{state.result.deliveredCustomers} delivered · {state.result.skippedCustomers} skipped · {formatMilli(BigInt(state.result.totalMilkMilli))} L · {formatPKR(BigInt(state.result.totalAmountPaisa))}</span><button type="button" className="button secondary" onClick={()=>window.print()}>Print receipt</button></div>:null}
    <div className="table-scroll"><table className="table"><thead><tr><th>House</th><th>Today</th><th>Milk (L)</th><th>Other products</th><th>Notes</th></tr></thead><tbody>{lines.map((line,index)=><tr key={line.id}><td><b>{line.name}</b><div className="subtitle">{line.code} · {line.address}</div></td><td><select value={line.deliveryStatus} onChange={event=>update(index,{deliveryStatus:event.target.value as Line["deliveryStatus"]})}><option value="delivered">Delivered normally</option><option value="changed">Changed quantity</option><option value="extra">Extra milk</option><option value="skipped">Skipped today</option><option value="paused">Customer paused</option></select></td><td><input inputMode="decimal" value={line.milkQuantity} disabled={!wasDelivered(line.deliveryStatus)} onChange={event=>update(index,{milkQuantity:event.target.value})}/>{wasDelivered(line.deliveryStatus)&&line.milkQuantity!==line.normalQuantity?<small className="changed-value">Normal: {line.normalQuantity} L</small>:null}</td><td><details><summary>Add products</summary><div className="extra-products">{products.map(product=><label key={product.sku}>{product.name}<input inputMode="decimal" placeholder={product.unit} value={line.products[product.sku]} disabled={!wasDelivered(line.deliveryStatus)} onChange={event=>update(index,{products:{...line.products,[product.sku]:event.target.value}})}/></label>)}</div></details></td><td><input value={line.notes} onChange={event=>update(index,{notes:event.target.value})}/></td></tr>)}</tbody></table></div>
    <div className="delivery-totals"><span><small>Customers</small><b>{totals.delivered} delivered · {totals.skipped} skipped</b></span><span><small>Total milk</small><b>{formatMilli(totals.milk)} L</b></span><span><small>Total value</small><b>{formatPKR(totals.amount)}</b></span><button type="button" className="button" disabled={pending||Boolean(state.result)||!customers.length} onClick={()=>setReviewing(true)}>Review &amp; Post</button></div>
    {reviewing?<div className="review-dialog" role="dialog" aria-modal="true"><div className="card review-card"><div className="section-title">Review daily deliveries</div><p>{businessDate}</p><div className="review-line"><span>Delivered customers</span><b>{totals.delivered}</b></div><div className="review-line"><span>Skipped or paused</span><b>{totals.skipped}</b></div><div className="review-line"><span>Milk going out</span><b>{formatMilli(totals.milk)} L</b></div><div className="review-total"><span>Customer charges</span><b>{formatPKR(totals.amount)}</b></div><div className="toolbar"><button type="button" className="button secondary" onClick={()=>setReviewing(false)}>Go back</button><button className="button" disabled={pending}>{pending?"Posting…":"Confirm and post"}</button></div></div></div>:null}
  </form>;
}
