"use server";
import { revalidatePath } from "next/cache";
import { requireSession } from "@/lib/auth";
import { postYogurtProduction,reverseYogurtProduction,yogurtProductionSchema } from "@/lib/services/yogurt-production";
import { logServerError } from "@/lib/logger";
export type ProductionState={error?:string;result?:{transactionNo:string;milkUsedMilli:string;yogurtOutputMilli:string;yogurtUnitCostPaisa:string;estimatedGrossProfitPaisa:string}};
export async function createYogurtBatch(_:ProductionState,formData:FormData):Promise<ProductionState>{const actor=await requireSession(["owner","manager"]);let payload:unknown;try{payload=JSON.parse(String(formData.get("payload")))}catch{return{error:"The Yogurt batch details are invalid."}}const parsed=yogurtProductionSchema.safeParse(payload);if(!parsed.success){const message=parsed.error.issues[0]?.message??"Check the Yogurt batch.";logServerError("yogurt_production.validation_failed",new Error(message),{actorId:actor.userId});return{error:message}}try{const result=await postYogurtProduction(parsed.data,actor.userId);for(const path of ["/production","/inventory","/deliveries","/dashboard","/reports"])revalidatePath(path);return{result}}catch(error){logServerError("yogurt_production.post_failed",error,{actorId:actor.userId,productionMode:parsed.data.productionMode,businessDate:parsed.data.businessDate});return{error:error instanceof Error?error.message:"The Yogurt batch could not be posted."}}}
export type ProductionReversalState={error?:string;success?:string};
export async function reverseYogurtBatch(_:ProductionReversalState,formData:FormData):Promise<ProductionReversalState>{const actor=await requireSession(["owner"]);try{const result=await reverseYogurtProduction(String(formData.get("transactionNo")??""),String(formData.get("reason")??""),actor.userId);for(const path of ["/production","/inventory","/deliveries","/dashboard","/reports"])revalidatePath(path);return{success:`Reversed as ${result.reversalNo}`}}catch(error){return{error:error instanceof Error?error.message:"The batch could not be reversed."}}}
