"use client";
import { useActionState,useMemo,useState } from "react";
import { formatMilli,formatPKR,quantityToMilli,rupeesToPaisa } from "@/lib/money";
import { calculateYogurtProduction } from "@/lib/yogurt-production-calculations";
import { createYogurtBatch,reverseYogurtBatch,type ProductionReversalState,type ProductionState } from "./actions";
type Kunda={id:string;size:"3"|"3.5"|"custom";customSize:string;count:string;notes:string};
const blankCosts={starter:"0",gas:"0",electricity:"0",labour:"0",packaging:"0",other:"0"};
export function ProductionForm({today,milkStockMilli,milkCostPaisa,yogurtRatePaisa}:{today:string;milkStockMilli:string;milkCostPaisa:string;yogurtRatePaisa:string}){
 const[state,action,pending]=useActionState(createYogurtBatch,{} as ProductionState),[open,setOpen]=useState(false),[review,setReview]=useState(false),[key]=useState(()=>crypto.randomUUID());
 const[date,setDate]=useState(today),[milk,setMilk]=useState(""),[price,setPrice]=useState(yogurtRatePaisa==="0"?"":(Number(yogurtRatePaisa)/100).toFixed(2)),[loose,setLoose]=useState("0"),[notes,setNotes]=useState(""),[payment,setPayment]=useState("");
 const[costs,setCosts]=useState(blankCosts),[kundas,setKundas]=useState<Kunda[]>([{id:"3kg",size:"3",customSize:"",count:"0",notes:""},{id:"35kg",size:"3.5",customSize:"",count:"0",notes:""}]);
 const calculated=useMemo(()=>{try{return calculateYogurtProduction({milkUsedMilli:quantityToMilli(milk),milkAverageCostPaisa:BigInt(milkCostPaisa),kundaEntries:kundas.filter(k=>Number(k.count)>0).map(k=>({sizeMilliKg:quantityToMilli(k.size==="custom"?k.customSize:k.size),numberOfKundas:Number(k.count)})),looseYogurtMilli:quantityToMilli(loose||"0"),additionalCostsPaisa:Object.values(costs).map(rupeesToPaisa),sellingRatePaisa:rupeesToPaisa(price)})}catch{return null}},[milk,price,loose,costs,kundas,milkCostPaisa]);
 const payload=JSON.stringify({businessDate:date,idempotencyKey:key,milkUsed:milk,sellingPrice:price,kundas:kundas.map(k=>({size:k.size,customSize:k.customSize,count:Number(k.count),notes:k.notes})),looseYogurt:loose,costs,processingPaymentMethod:payment||undefined,notes});
 const update=(id:string,change:Partial<Kunda>)=>setKundas(rows=>rows.map(row=>row.id===id?{...row,...change}:row));
 return <><button className="button production-primary" onClick={()=>setOpen(true)}>Create Yogurt Batch</button>{open?<div className="review-dialog"><form action={action} className="card production-form"><input type="hidden" name="payload" value={payload}/><div className="customer-heading"><div><div className="section-title">Create Yogurt Batch</div><div className="subtitle">Milk cost is loaded automatically from Fresh Milk inventory.</div></div><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Close</button></div>{state.error?<div className="form-error">{state.error}</div>:null}{state.result?<div className="form-success"><b>Posted {state.result.transactionNo}</b><span>{formatMilli(BigInt(state.result.milkUsedMilli))} L Milk converted into {formatMilli(BigInt(state.result.yogurtOutputMilli))} kg Yogurt.</span><button type="button" className="button secondary" onClick={()=>window.print()}>Print</button></div>:null}
 <div className="formgrid"><div className="field"><label>Business date</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>Fresh Milk used (liters)</label><input inputMode="decimal" value={milk} onChange={e=>setMilk(e.target.value)} autoFocus/><small>Available: {formatMilli(BigInt(milkStockMilli))} L</small></div><div className="field"><label>Yogurt selling price per kilogram</label><input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)}/></div><div className="field"><label>Loose Yogurt produced (kg)</label><input inputMode="decimal" value={loose} onChange={e=>setLoose(e.target.value)}/></div></div>
 <div className="section-title production-section">Kunda breakdown</div>{kundas.map(k=><div className="kunda-row" key={k.id}><select value={k.size} onChange={e=>update(k.id,{size:e.target.value as Kunda["size"]})}><option value="3">3 kg Kunda</option><option value="3.5">3.5 kg Kunda</option><option value="custom">Custom size</option></select>{k.size==="custom"?<input inputMode="decimal" placeholder="Weight in kg" value={k.customSize} onChange={e=>update(k.id,{customSize:e.target.value})}/>:null}<input inputMode="numeric" placeholder="Number of Kundas" value={k.count} onChange={e=>update(k.id,{count:e.target.value})}/><input placeholder="Note (optional)" value={k.notes} onChange={e=>update(k.id,{notes:e.target.value})}/><button type="button" className="button secondary" onClick={()=>setKundas(rows=>rows.filter(row=>row.id!==k.id))}>Remove</button></div>)}<button type="button" className="button secondary" onClick={()=>setKundas(rows=>[...rows,{id:crypto.randomUUID(),size:"custom",customSize:"",count:"1",notes:""}])}>Add custom Kunda size</button>
 <div className="section-title production-section">Additional production costs</div><div className="formgrid">{Object.keys(costs).map(name=><div className="field" key={name}><label>{name[0].toUpperCase()+name.slice(1)} cost</label><input inputMode="decimal" value={costs[name as keyof typeof costs]} onChange={e=>setCosts(old=>({...old,[name]:e.target.value}))}/></div>)}<div className="field"><label>Paid from (optional)</label><select value={payment} onChange={e=>setPayment(e.target.value)}><option value="">Not paid now</option><option value="cash">Cash</option><option value="bank">Bank</option><option value="easypaisa">Easypaisa</option><option value="jazzcash">JazzCash</option></select></div><div className="field"><label>Notes (optional)</label><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></div></div>
 {calculated?<div className="inventory-preview">{[["Milk cost",formatPKR(calculated.milkMaterialCostPaisa)],["Total Kunda weight",`${formatMilli(calculated.kundaOutputMilli)} kg`],["Loose Yogurt",`${loose||"0"} kg`],["Total Yogurt output",`${formatMilli(calculated.actualOutputMilli)} kg`],["Production costs",formatPKR(calculated.additionalCostPaisa)],["Total batch cost",formatPKR(calculated.totalProductionCostPaisa)],["Cost per kg",formatPKR(calculated.yogurtUnitCostPaisa)],["Estimated profit per kg",formatPKR(rupeesToPaisa(price)-calculated.yogurtUnitCostPaisa)],["Estimated total margin",formatPKR(calculated.estimatedGrossProfitPaisa)],["Production yield",`${formatMilli(calculated.yieldMilli)} kg/L`]].map(([label,value])=><span key={label}><small>{label}</small><b>{value}</b></span>)}</div>:null}<button type="button" className="button" disabled={!calculated||pending||Boolean(state.result)} onClick={()=>setReview(true)}>Review Yogurt Batch</button>
 {review&&calculated?<div className="review-dialog nested"><div className="card review-card"><div className="section-title">Confirm Yogurt production</div><div className="review-line"><span>Fresh Milk consumed</span><b>{milk} L</b></div><div className="review-line"><span>Yogurt produced</span><b>{formatMilli(calculated.actualOutputMilli)} kg</b></div><div className="review-line"><span>Total batch cost</span><b>{formatPKR(calculated.totalProductionCostPaisa)}</b></div><div className="review-line"><span>Selling price</span><b>{formatPKR(rupeesToPaisa(price))}/kg</b></div><div className="toolbar"><button type="button" className="button secondary" onClick={()=>setReview(false)}>Go back</button><button className="button" disabled={pending}>{pending?"Posting…":"Confirm and post"}</button></div></div></div>:null}</form></div>:null}</>;
}
export function ProductionReversal({transactionNo,status}:{transactionNo:string;status:string}){const[state,action,pending]=useActionState(reverseYogurtBatch,{} as ProductionReversalState),[open,setOpen]=useState(false);if(status!=="posted")return null;return <><button type="button" className="button secondary" onClick={()=>setOpen(true)}>Reverse</button>{open?<div className="review-dialog"><form action={action} className="card review-card"><input type="hidden" name="transactionNo" value={transactionNo}/><div className="section-title">Reverse {transactionNo}?</div><p>Only unused Yogurt production can be reversed safely.</p><div className="field"><label>Reason</label><textarea name="reason" required minLength={5}/></div>{state.error?<div className="form-error">{state.error}</div>:null}{state.success?<div className="form-success">{state.success}</div>:null}<div className="toolbar"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button" disabled={pending}>{pending?"Reversing…":"Confirm reversal"}</button></div></form></div>:null}</>}
export function ProductionPrintButton(){return <button type="button" className="button secondary" onClick={()=>window.print()}>Print</button>}
