import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { calculateDeliveryCharge } from "./delivery-calculations";
import { calculateStatementTotals, formatCustomerAccountSummaryMessage, formatCustomerStatementMessage, formatVendorAccountSummaryMessage, normalizePakistanPhone } from "./customer-statement-calculations";

describe("single daily household delivery workflow",()=>{
  it("charges delivered milk and products from snapshotted rates",()=>expect(calculateDeliveryCharge({deliveryStatus:"delivered",milkQuantity:"2",milkRatePaisa:20000n,products:[{sku:"BREAD-001",quantity:"1",ratePaisa:12000n}]})).toEqual({milkQuantityMilli:2000n,milkAmountPaisa:40000n,otherAmountPaisa:12000n,totalAmountPaisa:52000n}));
  it("does not charge or reduce stock for a skipped customer",()=>expect(calculateDeliveryCharge({deliveryStatus:"skipped",milkQuantity:"2",milkRatePaisa:20000n,products:[{sku:"BREAD-001",quantity:"1",ratePaisa:12000n}]})).toEqual({milkQuantityMilli:0n,milkAmountPaisa:0n,otherAmountPaisa:0n,totalAmountPaisa:0n}));
  it("calculates monthly quantities, charges, payments and balance from posted values",()=>expect(calculateStatementTotals({previousDebit:10000,previousCredit:0,currentDebit:52000,currentCredit:20000,allDebit:62000,allCredit:20000,deliveries:[{milkQuantityMilli:2000,milkAmountPaisa:40000,otherAmountPaisa:12000}]})).toEqual({previousBalance:10000n,currentCharges:52000n,payments:20000n,remainingBalance:42000n,milkQuantity:2000n,milkCharges:40000n,otherProductCharges:12000n}));
  it("builds the monthly WhatsApp balance and normalizes Pakistani numbers",()=>{const message=formatCustomerStatementMessage({customerName:"Ahmed",month:"2026-07",milkQuantity:2000n,milkCharges:40000n,otherProductCharges:12000n,previousBalance:10000n,payments:20000n,remainingBalance:42000n});expect(message).toContain("2 liters");expect(message).toContain("PKR 420.00");expect(normalizePakistanPhone("0300-1234567")).toBe("923001234567")});
  it("builds detailed real-time vendor and household WhatsApp summaries",()=>{const customerMessage=formatCustomerAccountSummaryMessage({customerName:"Ahmed",date:"2026-07-23",todayMilkQuantityMilli:2000n,todayChargesPaisa:40000n,previousOutstandingPaisa:15000n,totalChargesPaisa:320000n,totalPaymentsPaisa:280000n,currentOutstandingPaisa:40000n});const vendorMessage=formatVendorAccountSummaryMessage({vendorName:"Ali Dairy",date:"2026-07-23",todayMilkQuantityMilli:3000n,todayProcurementAmountPaisa:60000n,previousOutstandingPaisa:20000n,totalProcurementValuePaisa:500000n,totalPaymentsReceivedPaisa:450000n,currentRemainingPayablePaisa:50000n});expect(customerMessage).toContain("Assalamu Alaikum");expect(customerMessage).toContain("Today’s Milk Delivered");expect(vendorMessage).toContain("Today’s Milk Supplied");expect(vendorMessage).toContain("Remaining Payable Balance");});
  it("exposes only the daily-delivery navigation and no obsolete business page",()=>{const sidebar=readFileSync(resolve("src/components/sidebar.tsx"),"utf8"),legacyPath="/"+["rou","tes"].join("");expect(sidebar).toContain("Daily Deliveries");expect(sidebar).not.toContain(legacyPath);expect(existsSync(resolve("src/app/(app)",["rou","tes"].join(""),"page.tsx"))).toBe(false)});
  it("creates customers without an obsolete grouping assignment",()=>{const source=readFileSync(resolve("src/app/(app)/customers/actions.ts"),"utf8"),legacyField=["route","Id"].join("");expect(source).not.toContain(legacyField);expect(source).toContain("defaultQuantityMilli");expect(source).toContain("deliveryDays")});
  it("loads every active household into one sheet and pre-fills normal quantity",()=>{const page=readFileSync(resolve("src/app/(app)/deliveries/page.tsx"),"utf8"),sheet=readFileSync(resolve("src/app/(app)/deliveries/delivery-sheet.tsx"),"utf8");expect(page).toContain('active: true, customerType: "household"');expect(sheet).toContain("milkQuantity: customer.normalQuantity");expect(sheet).toContain("Changed quantity");expect(sheet).toContain("Extra milk")});
  it("enforces one posted batch per date and one posted customer delivery per date",()=>{const migration=readFileSync(resolve("scripts/migrate.ts"),"utf8");expect(migration).toContain('delivery_batches: [{ key: { transactionNo: 1 }, unique: true }, { key: { businessDate: 1 }, unique: true');expect(migration).toContain('{ key: { customerId: 1, businessDate: 1 }, unique: true')});
  it("posts the sheet without requiring an obsolete grouping identifier",()=>{const service=readFileSync(resolve("src/lib/services/delivery.ts"),"utf8"),legacyField=["route","Id"].join("");expect(service).not.toContain(legacyField);for(const collection of ["delivery_batches","customer_deliveries","party_ledger_entries","inventory_movements","financial_transactions","audit_logs","idempotency_records"])expect(service).toContain(collection)});
  it("allows newly added households to be appended after the daily batch was posted",()=>{const service=readFileSync(resolve("src/lib/services/delivery.ts"),"utf8"),page=readFileSync(resolve("src/app/(app)/deliveries/page.tsx"),"utf8");expect(service).toContain("pendingHouseholds");expect(service).toContain('action: existing ? "supplement" : "post"');expect(service).toContain("delivery_batches\").updateOne");expect(page).toContain("postedCustomerIds");expect(page).toContain("newly added household customer")});
  it("treats partial and advance payments as credits against outstanding balance",()=>{const totals=calculateStatementTotals({previousDebit:0,previousCredit:0,currentDebit:100000,currentCredit:125000,allDebit:100000,allCredit:125000,deliveries:[]});expect(totals.payments).toBe(125000n);expect(totals.remainingBalance).toBe(-25000n)});
  it("keeps dashboards and reports free of obsolete delivery-group filters",()=>{const legacyWord=["route","Performance"].join(""),dashboard=readFileSync(resolve("src/app/(app)/dashboard/page.tsx"),"utf8"),reports=readFileSync(resolve("src/app/(app)/reports/page.tsx"),"utf8");expect(dashboard).not.toContain(legacyWord);expect(reports).not.toContain(legacyWord);expect(dashboard).toContain("Households delivered")});
});
