import { db } from "@/lib/db";
import { addDays } from "@/lib/date-utils";
import { DateFilter } from "@/components/date-filter";
import { formatMilli,formatPKR,integerToBigInt } from "@/lib/money";
import { karachiBusinessDate } from "@/lib/queries";
import { YOGURT_PRODUCTION_DEFAULTS } from "@/lib/yogurt-production-calculations";
export const dynamic="force-dynamic";
export default async function ReportsPage({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
 const filters=await searchParams,database=await db(),businessDate=karachiBusinessDate(),month=businessDate.slice(0,7),from=filters.from??`${month}-01`,to=filters.to?addDays(filters.to,1):new Date(Date.UTC(Number(month.split("-")[0]),Number(month.split("-")[1]),1)).toISOString().slice(0,10);
 const[production,sales,transactions,settings]=await Promise.all([
  database.collection("production_batches").aggregate([{$match:{businessDate:{$gte:from,$lt:to},status:"posted",yogurtProductSku:"YOG-001"}},{$group:{_id:"$businessDate",milk:{$sum:{$ifNull:["$actualMilkUsedMilli","$milkUsedMilli"]}},output:{$sum:{$ifNull:["$actualYogurtOutputMilli","$actualOutputMilli"]}},loss:{$sum:"$processingLossMilli"},variance:{$sum:"$yieldVarianceMilli"},automatic:{$sum:{$cond:[{$eq:["$productionMode","automatic"]},1,0]}},manual:{$sum:{$cond:[{$eq:["$productionMode","manual"]},1,0]}},lowYield:{$sum:{$cond:[{$lt:["$actualYieldMilli",{$subtract:["$standardYieldMilli","$yieldToleranceMilli"]}]},1,0]}},loose:{$sum:"$looseYogurtMilli"},materialCost:{$sum:"$milkMaterialCostPaisa"},additionalCost:{$sum:"$additionalCostPaisa"},totalCost:{$sum:"$totalProductionCostPaisa"},estimatedProfit:{$sum:"$estimatedGrossProfitPaisa"},threeKg:{$sum:{$sum:{$map:{input:{$filter:{input:"$kundaEntries",as:"k",cond:{$eq:["$$k.sizeType","3"]}}},as:"k",in:"$$k.numberOfKundas"}}}},threeHalfKg:{$sum:{$sum:{$map:{input:{$filter:{input:"$kundaEntries",as:"k",cond:{$eq:["$$k.sizeType","3.5"]}}},as:"k",in:"$$k.numberOfKundas"}}}},custom:{$sum:{$sum:{$map:{input:{$filter:{input:"$kundaEntries",as:"k",cond:{$eq:["$$k.sizeType","custom"]}}},as:"k",in:"$$k.numberOfKundas"}}}}}},{$sort:{_id:1}}]).toArray(),
  database.collection("inventory_movements").aggregate([{$match:{businessDate:{$gte:from,$lt:to},status:"posted",productSku:"YOG-001",quantityMilli:{$lt:0}}},{$group:{_id:null,quantity:{$sum:{$abs:"$quantityMilli"}},revenue:{$sum:"$revenuePaisa"},cogs:{$sum:"$costOfGoodsSoldPaisa"},profit:{$sum:"$grossProfitPaisa"}}}]).next(),
  database.collection("financial_transactions").find({businessDate:{$gte:from,$lt:to},status:"posted"}).sort({businessDate:-1}).limit(100).toArray(),
  database.collection("business_settings").findOne({_id:"default" as never}),
 ]);
 const totals=production.reduce((total,row)=>({milk:total.milk+integerToBigInt(row.milk),output:total.output+integerToBigInt(row.output),loss:total.loss+integerToBigInt(row.loss),automatic:total.automatic+Number(row.automatic??0),manual:total.manual+Number(row.manual??0),lowYield:total.lowYield+Number(row.lowYield??0),loose:total.loose+integerToBigInt(row.loose),material:total.material+integerToBigInt(row.materialCost),additional:total.additional+integerToBigInt(row.additionalCost),cost:total.cost+integerToBigInt(row.totalCost)}),{milk:0n,output:0n,loss:0n,automatic:0,manual:0,lowYield:0,loose:0n,material:0n,additional:0n,cost:0n}),sold=integerToBigInt(sales?.quantity),revenue=integerToBigInt(sales?.revenue),cogs=integerToBigInt(sales?.cogs),profit=integerToBigInt(sales?.profit),margin=revenue>0n?profit*10000n/revenue:0n,averageCost=totals.output>0n?totals.cost*1000n/totals.output:0n,averageYield=totals.milk>0n?totals.output*1000n/totals.milk:0n;
 const cards=[["Automatic / Manual batches",`${totals.automatic} / ${totals.manual}`],["Milk converted",`${formatMilli(totals.milk)} kg`],["Yogurt produced",`${formatMilli(totals.output)} kg`],["Production loss",`${formatMilli(totals.loss)} kg`],["Average actual yield",`${formatMilli(averageYield*100n)}%`],["Standard yield",`${formatMilli(integerToBigInt(settings?.yogurtAutomaticYieldMilli,YOGURT_PRODUCTION_DEFAULTS.standardYieldMilli)*100n)}%`],["Low-yield batches",String(totals.lowYield)],["Yogurt sold",`${formatMilli(sold)} kg`],["Produced minus sold",`${formatMilli(totals.output-sold)} kg`],["Milk material cost",formatPKR(totals.material)],["Additional costs",formatPKR(totals.additional)],["Average production cost",`${formatPKR(averageCost)} / kg`],["Yogurt revenue",formatPKR(revenue)],["Yogurt COGS",formatPKR(cogs)],["Yogurt gross profit",formatPKR(profit)],["Gross margin",`${formatMilli(margin)}%`]];
   return <div className="content"><div className="customer-heading"><div><div className="title">Reports</div><div className="subtitle">Posted financial transactions and Yogurt production performance.</div></div><div className="toolbar"><DateFilter/></div></div><div className="section-title production-section">Yogurt production analytics</div><section className="grid kpis production-kpis">{cards.map(([label,value])=><article className="card" key={label}><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div></article>)}</section><div className="card table-card"><div className="section-title">Daily Yogurt yield, loss and Kunda output</div>{production.length?<div className="table-scroll"><table className="table"><thead><tr><th>Date</th><th>Mode A/M</th><th>Milk</th><th>Yogurt</th><th>Loss</th><th>Yield</th><th>Variance</th><th>3 kg</th><th>3.5 kg</th><th>Custom</th><th>Loose</th><th>Cost/kg</th><th>Profit/kg</th></tr></thead><tbody>{production.map(row=>{const milk=integerToBigInt(row.milk),output=integerToBigInt(row.output),cost=integerToBigInt(row.totalCost),estimated=integerToBigInt(row.estimatedProfit);return <tr key={String(row._id)}><td>{String(row._id)}</td><td>{Number(row.automatic??0)} / {Number(row.manual??0)}</td><td>{formatMilli(milk)} kg</td><td>{formatMilli(output)} kg</td><td>{formatMilli(integerToBigInt(row.loss))} kg</td><td>{formatMilli((milk>0n?output*1000n/milk:0n)*100n)}%</td><td>{formatMilli(integerToBigInt(row.variance))} kg</td><td>{Number(row.threeKg??0)}</td><td>{Number(row.threeHalfKg??0)}</td><td>{Number(row.custom??0)}</td><td>{formatMilli(integerToBigInt(row.loose))} kg</td><td>{formatPKR(output>0n?cost*1000n/output:0n)}</td><td>{formatPKR(output>0n?estimated*1000n/output:0n)}</td></tr>})}</tbody></table></div>:<div className="empty-state"><b>No Yogurt production in selected period</b><span>Posted Yogurt batches will appear here.</span></div>}</div><div className="card table-card"><div className="section-title">Posted financial transactions</div>{transactions.length?<div className="table-scroll"><table className="table"><thead><tr><th>Transaction</th><th>Date</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody>{transactions.map(row=><tr key={row._id.toString()}><td>{String(row.transactionNo)}</td><td>{String(row.businessDate)}</td><td>{String(row.kind).replaceAll("_"," ")}</td><td>{formatPKR(integerToBigInt(row.amountPaisa))}</td><td><span className="badge">{String(row.status)}</span></td></tr>)}</tbody></table></div>:<div className="empty-state"><b>No posted transactions</b><span>Financial transactions for the selected period will appear here.</span></div>}</div></div>;
}
