import { notFound } from "next/navigation";
import { PrintButton } from "@/components/print-button";
import { customerStatementMessage, getCustomerStatement, normalizePakistanPhone } from "@/lib/customer-statement";
import { formatMilli, formatPKR, integerToBigInt } from "@/lib/money";
import { karachiBusinessDate } from "@/lib/queries";
export const dynamic="force-dynamic";

export default async function StatementPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{month?:string}>}){
  const{id}=await params,query=await searchParams,month=query.month??karachiBusinessDate().slice(0,7);let statement;
  try{statement=await getCustomerStatement(id,month)}catch{notFound()}
  const message=encodeURIComponent(customerStatementMessage(statement));
  return <div className="content statement"><div className="customer-heading"><div><div className="title">{String(statement.customer.name)} · Monthly Statement</div><div className="subtitle">{month} · {String(statement.customer.address??"")}</div></div><div className="toolbar"><PrintButton/><a className="button secondary" href={`/api/customers/${id}/statement?month=${month}&format=pdf`}>PDF</a><a className="button secondary" href={`/api/customers/${id}/statement?month=${month}&format=xlsx`}>Excel</a><a className="button secondary" href={`/api/customers/${id}/statement?month=${month}&format=csv`}>CSV</a><a className="button" href={`https://wa.me/${normalizePakistanPhone(String(statement.customer.whatsapp||statement.customer.phone))}?text=${message}`} target="_blank" rel="noreferrer">WhatsApp</a></div></div><section className="grid kpis"><article className="card"><div className="kpi-label">Previous balance</div><div className="kpi-value">{formatPKR(statement.previousBalance)}</div></article><article className="card"><div className="kpi-label">Current charges</div><div className="kpi-value">{formatPKR(statement.currentCharges)}</div></article><article className="card"><div className="kpi-label">Payments received</div><div className="kpi-value">{formatPKR(statement.payments)}</div></article><article className="card"><div className="kpi-label">Remaining balance</div><div className="kpi-value">{formatPKR(statement.remainingBalance)}</div></article></section><div className="card table-card"><div className="section-title">Daily delivery breakdown</div><table className="table"><thead><tr><th>Date</th><th>Status</th><th>Milk</th><th>Milk charge</th><th>Other products</th><th>Total</th></tr></thead><tbody>{statement.deliveries.map(row=><tr key={row._id.toString()}><td>{row.businessDate}</td><td>{row.deliveryStatus}</td><td>{formatMilli(integerToBigInt(row.milkQuantityMilli))} L</td><td>{formatPKR(integerToBigInt(row.milkAmountPaisa))}</td><td>{formatPKR(integerToBigInt(row.otherAmountPaisa))}</td><td>{formatPKR(integerToBigInt(row.amountPaisa))}</td></tr>)}</tbody></table></div></div>;
}
