import { notFound } from "next/navigation";
import { ObjectId } from "mongodb";
import { PrintButton } from "@/components/print-button";
import { customerStatementMessage, getCustomerStatement, normalizePakistanPhone } from "@/lib/customer-statement";
import { db } from "@/lib/db";
import { formatMilli, formatPKR, integerToBigInt } from "@/lib/money";
import { karachiBusinessDate } from "@/lib/queries";
export const dynamic="force-dynamic";

export default async function StatementPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{month?:string}>}){
  const{id}=await params,query=await searchParams,month=query.month??karachiBusinessDate().slice(0,7);let statement;
  try{statement=await getCustomerStatement(id,month)}catch{notFound()}
  if(statement.customer.customerType==="shop"){
    const database=await db(),entries=await database.collection("party_ledger_entries").find({partyType:"customer",partyId:new ObjectId(id),status:"posted"}).sort({businessDate:1,date:1}).toArray();
    const rows=entries.map((entry,index)=>({_id:entry._id,id:entry._id.toString(),businessDate:String(entry.businessDate),transactionNo:String(entry.transactionNo),description:String(entry.description??""),debit:integerToBigInt(entry.debitPaisa),credit:integerToBigInt(entry.creditPaisa),running:entries.slice(0,index+1).reduce((sum,item)=>sum+integerToBigInt(item.debitPaisa)-integerToBigInt(item.creditPaisa),0n)})),running=rows.at(-1)?.running??0n,number=normalizePakistanPhone(String(statement.customer.whatsapp||statement.customer.phone||"")),shopMessage=encodeURIComponent(`Assalam-o-Alaikum ${statement.customer.name}. Your remaining shop Udhaar balance is ${formatPKR(running)}. Please send payment when convenient. Thank you.`);
    return <div className="content statement"><div className="customer-heading"><div><div className="title">{String(statement.customer.name)} · Shop Udhaar Statement</div><div className="subtitle">Lifetime running history · balances do not reset monthly</div></div><div className="toolbar"><PrintButton/>{number?<a className="button" href={`https://wa.me/${number}?text=${shopMessage}`} target="_blank" rel="noreferrer">Send Balance on WhatsApp</a>:<button className="button" disabled>Add WhatsApp number to send</button>}</div></div><section className="grid kpis"><article className="card"><div className="kpi-label">Total Credit purchases</div><div className="kpi-value">{formatPKR(rows.reduce((sum,row)=>sum+row.debit,0n))}</div></article><article className="card"><div className="kpi-label">Total payments / credits</div><div className="kpi-value">{formatPKR(rows.reduce((sum,row)=>sum+row.credit,0n))}</div></article><article className="card"><div className="kpi-label">Current Udhaar</div><div className="kpi-value">{formatPKR(running)}</div></article></section><div className="card table-card table-scroll"><div className="section-title">Lifetime transactions</div><table className="table"><thead><tr><th>Date</th><th>Transaction</th><th>Details</th><th>Credit purchase</th><th>Payment / credit</th><th>Running balance</th></tr></thead><tbody>{rows.map(row=><tr key={row._id.toString()}><td>{String(row.businessDate)}</td><td>{String(row.transactionNo)}</td><td>{String(row.description??"")}</td><td>{row.debit?formatPKR(row.debit):"—"}</td><td>{row.credit?formatPKR(row.credit):"—"}</td><td><b>{formatPKR(row.running)}</b></td></tr>)}</tbody></table></div></div>;
  }
  const message=encodeURIComponent(customerStatementMessage(statement));
  return <div className="content statement"><div className="customer-heading"><div><div className="title">{String(statement.customer.name)} · Monthly Statement</div><div className="subtitle">{month} · {String(statement.customer.address??"")}</div></div><div className="toolbar"><PrintButton/><a className="button secondary" href={`/api/customers/${id}/statement?month=${month}&format=pdf`}>PDF</a><a className="button secondary" href={`/api/customers/${id}/statement?month=${month}&format=xlsx`}>Excel</a><a className="button secondary" href={`/api/customers/${id}/statement?month=${month}&format=csv`}>CSV</a><a className="button" href={`https://wa.me/${normalizePakistanPhone(String(statement.customer.whatsapp||statement.customer.phone))}?text=${message}`} target="_blank" rel="noreferrer">WhatsApp</a></div></div><section className="grid kpis"><article className="card"><div className="kpi-label">Previous balance</div><div className="kpi-value">{formatPKR(statement.previousBalance)}</div></article><article className="card"><div className="kpi-label">Current charges</div><div className="kpi-value">{formatPKR(statement.currentCharges)}</div></article><article className="card"><div className="kpi-label">Payments received</div><div className="kpi-value">{formatPKR(statement.payments)}</div></article><article className="card"><div className="kpi-label">Remaining balance</div><div className="kpi-value">{formatPKR(statement.remainingBalance)}</div></article></section><div className="card table-card"><div className="section-title">Daily delivery breakdown</div><table className="table"><thead><tr><th>Date</th><th>Status</th><th>Milk</th><th>Milk charge</th><th>Other products</th><th>Total</th></tr></thead><tbody>{statement.deliveries.map(row=><tr key={row._id.toString()}><td>{row.businessDate}</td><td>{row.deliveryStatus}</td><td>{formatMilli(integerToBigInt(row.milkQuantityMilli))} L</td><td>{formatPKR(integerToBigInt(row.milkAmountPaisa))}</td><td>{formatPKR(integerToBigInt(row.otherAmountPaisa))}</td><td>{formatPKR(integerToBigInt(row.amountPaisa))}</td></tr>)}</tbody></table></div></div>;
}
