import { DatabaseModulePage } from "@/components/database-module-page";
export const dynamic = "force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{from?:string;to?:string;q?:string}>}) {
  const {from,to,q}=await searchParams;
  return <DatabaseModulePage title="Notifications" description="Real operational exceptions generated by workflows." collection="notifications" columns={[["Severity","severity"],["Alert","title"],["Details","message"],["Status","status"],["Created","createdAt"]]} dateField="createdAt" from={from} to={to} q={q}/>;
}
