"use client";
import { useActionState, useEffect, useMemo, useRef, useState } from "react";
import { formatMilli, formatPKR, multiplyQuantityRate, quantityToMilli, rupeesToPaisa } from "@/lib/money";
import { postProcurement, type ProcurementState } from "./actions";
type Vendor={id:string;code:string;name:string;rate:string}; type Line=Vendor&{quantity:string;notes:string;noPickup:boolean};
const initialState:ProcurementState={};
export function ProcurementForm({vendors,today}:{vendors:Vendor[];today:string}){
 const [state,action,pending]=useActionState(postProcurement,initialState); const [date,setDate]=useState(today); const [shift,setShift]=useState(new Date().getHours()<14?"morning":"evening"); const [key,setKey]=useState(()=>crypto.randomUUID()); const [reviewing,setReviewing]=useState(false); const handled=useRef<string|undefined>(undefined);
 const blank=()=>vendors.map(v=>({...v,quantity:"",notes:"",noPickup:false})); const [lines,setLines]=useState<Line[]>(blank);
 const totals=useMemo(()=>lines.reduce((s,l)=>{if(!l.quantity||l.noPickup)return s;try{const q=quantityToMilli(l.quantity);return{quantity:s.quantity+q,amount:s.amount+multiplyQuantityRate(q,rupeesToPaisa(l.rate))}}catch{return s}},{quantity:0n,amount:0n}),[lines]);
 const invalid=lines.some(l=>l.quantity!==""&&!l.noPickup&&!/^\d+(\.\d{1,3})?$/.test(l.quantity));
 useEffect(()=>{if(state.result&&handled.current!==state.result.transactionNo){handled.current=state.result.transactionNo;setLines(vendors.map(v=>({...v,quantity:"",notes:"",noPickup:false})));setKey(crypto.randomUUID());setReviewing(false)}},[state.result,vendors]);
 const payload=JSON.stringify({businessDate:date,shift,idempotencyKey:key,lines:lines.map(({id,quantity,notes,noPickup})=>({vendorId:id,quantity,notes,noPickup}))});
 return <form action={action} className="card table-card"><input type="hidden" name="payload" value={payload}/><div className="toolbar procurement-toolbar"><div className="toolbar"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={shift} onChange={e=>setShift(e.target.value)}><option value="morning">Morning</option><option value="evening">Evening</option><option value="custom">Custom</option></select></div><span className="badge">{lines.length} active vendors</span></div>
 {state.error?<div className="form-error" role="alert">{state.error}</div>:null}{state.result?<div className="form-success"><b>Receipt {state.result.transactionNo}</b><span>{formatPKR(BigInt(state.result.totalAmountPaisa))}</span><button type="button" className="button secondary" onClick={()=>window.print()}>Print</button></div>:null}
 <div className="table-scroll"><table className="table"><thead><tr><th>Vendor</th><th>Quantity (L)</th><th>Rate / L</th><th>Amount</th><th>Notes</th><th>No pickup</th></tr></thead><tbody>{lines.map((l,i)=>{let amount=0n;try{amount=l.quantity?multiplyQuantityRate(quantityToMilli(l.quantity),rupeesToPaisa(l.rate)):0n}catch{}const bad=l.quantity!==""&&!/^\d+(\.\d{1,3})?$/.test(l.quantity);return <tr key={l.id}><td><b>{l.name}</b><div className="subtitle">{l.code}</div></td><td><input inputMode="decimal" value={l.quantity} disabled={l.noPickup} aria-invalid={bad} onChange={e=>setLines(c=>c.map((x,n)=>n===i?{...x,quantity:e.target.value}:x))}/>{bad?<small className="field-error">Enter liters with up to 3 decimals.</small>:null}</td><td><input value={l.rate} readOnly/></td><td>{formatPKR(amount)}</td><td><input value={l.notes} onChange={e=>setLines(c=>c.map((x,n)=>n===i?{...x,notes:e.target.value}:x))}/></td><td><input type="checkbox" checked={l.noPickup} onChange={e=>setLines(c=>c.map((x,n)=>n===i?{...x,noPickup:e.target.checked,quantity:e.target.checked?"":x.quantity}:x))}/></td></tr>})}</tbody></table></div>
 <div className="procurement-totals"><span><small>Total milk</small><b>{formatMilli(totals.quantity)} L</b></span><span><small>Total cost</small><b>{formatPKR(totals.amount)}</b></span><button type="button" className="button" disabled={pending||invalid||totals.quantity===0n} onClick={()=>setReviewing(true)}>Review &amp; post batch</button></div>
 {reviewing?<div className="review-dialog" role="dialog" aria-modal="true"><div className="card review-card"><div className="section-title">Review milk received</div><p>{date} · {shift}</p>{lines.filter(l=>l.quantity&&!l.noPickup).map(l=><div className="review-line" key={l.id}><span>{l.name}</span><b>{l.quantity} L · {formatPKR(multiplyQuantityRate(quantityToMilli(l.quantity),rupeesToPaisa(l.rate)))}</b></div>)}<div className="review-total"><span>Grand total</span><b>{formatPKR(totals.amount)}</b></div><div className="toolbar"><button type="button" className="button secondary" onClick={()=>setReviewing(false)}>Go back</button><button className="button" disabled={pending}>{pending?"Posting…":"Confirm and post"}</button></div></div></div>:null}</form>
}
