import { Long, type Document } from "mongodb";
import { z } from "zod";
import { transaction } from "../db";
import { transactionNo } from "../ids";
import { inventoryReceiptLine, isEligibleManualReceiptProduct, isManualReceiptSku } from "../inventory-calculations";
import { integerToBigInt, quantityToMilli, rupeesToPaisa } from "../money";
import { eggPurchaseCalculation, normalizeEggQuantity, validatePiecesPerTray } from "../egg-units";

const lineSchema=z.object({productSku:z.string().max(30),quantity:z.string(),buyingPrice:z.string(),sellingPrice:z.string().optional(),keepExistingSellingPrice:z.boolean().default(false),receivingUnit:z.enum(["piece","tray"]).optional(),pieceSellingPrice:z.string().optional(),traySellingPrice:z.string().optional()});
export const inventoryReceiptSchema=z.object({businessDate:z.iso.date(),idempotencyKey:z.uuid(),supplierName:z.string().trim().max(120).optional(),supplierReference:z.string().trim().max(120).optional(),paymentStatus:z.enum(["paid","partial","unpaid"]),paymentMethod:z.enum(["cash","bank","easypaisa","jazzcash"]).optional(),paidAmount:z.string().optional(),notes:z.string().trim().max(500).optional(),attachmentKey:z.string().max(500).optional(),lines:z.array(lineSchema).min(1).max(20)});
export type InventoryReceiptInput=z.infer<typeof inventoryReceiptSchema>;
const duplicate=(error:unknown)=>Boolean(error&&typeof error==="object"&&"code" in error&&error.code===11000);

export async function postInventoryReceipt(raw:InventoryReceiptInput,actorId:string){const input=inventoryReceiptSchema.parse(raw);return transaction(async(database,session)=>{
  const previous=await database.collection("idempotency_records").findOne({key:input.idempotencyKey},{session});if(previous)return previous.result as {transactionNo:string;subtotalPaisa:string;paidAmountPaisa:string;balances:Array<{sku:string;stockMilli:string;averageCostPaisa:string;retailRatePaisa:string}>};
  const settings=await database.collection("business_settings").findOne({_id:"default" as never},{session}),today=new Intl.DateTimeFormat("en-CA",{timeZone:String(settings?.timezone??"Asia/Karachi"),year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),dayDifference=Math.round((new Date(`${today}T00:00:00Z`).getTime()-new Date(`${input.businessDate}T00:00:00Z`).getTime())/86_400_000),allowedBackdateDays=Number(settings?.allowedBackdateDays??3);if(dayDifference<0)throw new Error("Future inventory receipts are not allowed.");if(dayDifference>allowedBackdateDays)throw new Error(`Inventory receipts can only be backdated ${allowedBackdateDays} days.`);
  if(new Set(input.lines.map(line=>line.productSku)).size!==input.lines.length)throw new Error("Each product can appear only once on a receipt.");
  const now=new Date(),number=transactionNo("INV"),receiptLines:Document[]=[],movements:Document[]=[],rateChanges:Document[]=[],balances:Array<{sku:string;stockMilli:string;averageCostPaisa:string;retailRatePaisa:string}>=[];let subtotal=0n;
  for(const[index,line]of input.lines.entries()){
    if(!isManualReceiptSku(line.productSku))throw new Error(line.productSku==="MILK-001"?"Fresh Milk stock is updated through Vendor Milk Procurement.":line.productSku==="YOG-001"?"Yogurt stock must be created through Yogurt Production.":"This product cannot be received through Add Inventory.");
    const product=await database.collection("products").findOne({sku:line.productSku},{session});
    if(!product||!isEligibleManualReceiptProduct({sku:String(product.sku),active:Boolean(product.active),inventoryManaged:Boolean(product.inventoryManaged),allowManualStockReceipt:Boolean(product.allowManualStockReceipt),internalOnly:Boolean(product.internalOnly)}))throw new Error("This product is inactive or not eligible for inventory receiving.");
    if(line.productSku==="EGG-001"){
      const piecesPerTray=validatePiecesPerTray(product.piecesPerTray),receivingUnit=line.receivingUnit??"tray",normalized=normalizeEggQuantity(line.quantity,receivingUnit,piecesPerTray),buyingPrice=rupeesToPaisa(line.buyingPrice),previousStockMilli=integerToBigInt(product.stockMilli),previousAverageCostPaisa=integerToBigInt(product.averageCostPaisa),previousPieceRate=integerToBigInt(product.pieceSellingRatePaisa,product.retailRatePaisa),previousTrayRate=integerToBigInt(product.traySellingRatePaisa);
      let pieceRate=previousPieceRate,trayRate=previousTrayRate;if(!line.keepExistingSellingPrice){pieceRate=rupeesToPaisa(line.pieceSellingPrice??"");trayRate=rupeesToPaisa(line.traySellingPrice??"");if(pieceRate<=0n||trayRate<=0n)throw new Error("Enter valid Egg selling prices per piece and per tray.");}else if(pieceRate<=0n||trayRate<=0n)throw new Error("The first Egg receipt requires selling prices per piece and per tray.");
      const calculated=eggPurchaseCalculation({enteredQuantity:normalized.enteredQuantity,enteredUnit:receivingUnit,buyingPricePerEnteredUnitPaisa:buyingPrice,piecesPerTray,existingStockMilli:previousStockMilli,existingAverageCostPerPiecePaisa:previousAverageCostPaisa});subtotal+=calculated.purchaseTotalPaisa;
      receiptLines.push({productId:product._id,productSku:"EGG-001",productNameSnapshot:String(product.name),unitSnapshot:"piece",enteredQuantity:Long.fromBigInt(normalized.enteredQuantity),enteredUnit:receivingUnit,piecesPerTraySnapshot:piecesPerTray,normalizedPieceQuantity:Long.fromBigInt(calculated.normalizedPieces),quantityMilli:Long.fromBigInt(calculated.normalizedQuantityMilli),buyingPricePerEnteredUnitPaisa:Long.fromBigInt(buyingPrice),purchaseUnitCostPaisa:Long.fromBigInt(calculated.purchaseCostPerPiecePaisa),pieceSellingRatePaisa:Long.fromBigInt(pieceRate),traySellingRatePaisa:Long.fromBigInt(trayRate),sellingUnitRatePaisa:Long.fromBigInt(pieceRate),linePurchaseTotalPaisa:Long.fromBigInt(calculated.purchaseTotalPaisa),previousStockMilli:Long.fromBigInt(previousStockMilli),resultingStockMilli:Long.fromBigInt(calculated.resultingStockMilli),previousAverageCostPaisa:Long.fromBigInt(previousAverageCostPaisa),resultingAverageCostPaisa:Long.fromBigInt(calculated.resultingAverageCostPerPiecePaisa),previousSellingRatePaisa:Long.fromBigInt(previousPieceRate),previousPieceSellingRatePaisa:Long.fromBigInt(previousPieceRate),previousTraySellingRatePaisa:Long.fromBigInt(previousTrayRate)});
      movements.push({transactionNo:number,lineNo:index+1,productId:product._id,productSku:"EGG-001",location:"main-shop",type:"inventory-receipt",enteredQuantity:Long.fromBigInt(normalized.enteredQuantity),enteredUnit:receivingUnit,piecesPerTray:piecesPerTray,normalizedPieces:Long.fromBigInt(calculated.normalizedPieces),quantityMilli:Long.fromBigInt(calculated.normalizedQuantityMilli),unitCostPaisa:Long.fromBigInt(calculated.purchaseCostPerPiecePaisa),buyingPricePerEnteredUnitPaisa:Long.fromBigInt(buyingPrice),resultingAverageCostPaisa:Long.fromBigInt(calculated.resultingAverageCostPerPiecePaisa),businessDate:input.businessDate,date:now,sourceType:"inventory_receipt",sourceTransactionNo:number,status:"posted",createdAt:now,createdBy:actorId});
      const effectiveFrom=new Date(`${input.businessDate}T00:00:00Z`);for(const[unit,previous,rate]of [["piece",previousPieceRate,pieceRate],["tray",previousTrayRate,trayRate]] as const)if(rate!==previous){await database.collection("product_rate_history").updateMany({productId:product._id,saleUnit:unit,effectiveTo:null,effectiveFrom:{$lt:effectiveFrom}},{$set:{effectiveTo:effectiveFrom,updatedAt:now,updatedBy:actorId}},{session});rateChanges.push({productId:product._id,productSku:"EGG-001",saleUnit:unit,previousRatePaisa:Long.fromBigInt(previous),ratePaisa:Long.fromBigInt(rate),effectiveFrom,effectiveTo:null,businessDate:input.businessDate,source:"inventory_receipt",sourceTransactionNo:number,createdAt:now,createdBy:actorId});}
      const stockUpdate=await database.collection("products").updateOne({_id:product._id,stockMilli:product.stockMilli,averageCostPaisa:product.averageCostPaisa},{$set:{stockMilli:Long.fromBigInt(calculated.resultingStockMilli),averageCostPaisa:Long.fromBigInt(calculated.resultingAverageCostPerPiecePaisa),retailRatePaisa:Long.fromBigInt(pieceRate),pieceSellingRatePaisa:Long.fromBigInt(pieceRate),traySellingRatePaisa:Long.fromBigInt(trayRate),lastStockReceivedAt:now,updatedAt:now,updatedBy:actorId}},{session});if(!stockUpdate.modifiedCount)throw new Error("Egg stock changed while saving. Please review and try again.");
      balances.push({sku:"EGG-001",stockMilli:calculated.resultingStockMilli.toString(),averageCostPaisa:calculated.resultingAverageCostPerPiecePaisa.toString(),retailRatePaisa:pieceRate.toString()});continue;
    }
    const quantityMilli=quantityToMilli(line.quantity),purchaseUnitCostPaisa=rupeesToPaisa(line.buyingPrice);if(quantityMilli<=0n||purchaseUnitCostPaisa<=0n)throw new Error("Quantity and buying price must be greater than zero.");
    const previousStockMilli=integerToBigInt(product.stockMilli),previousAverageCostPaisa=integerToBigInt(product.averageCostPaisa),previousSellingRatePaisa=integerToBigInt(product.retailRatePaisa);
    let sellingUnitRatePaisa=previousSellingRatePaisa;if(!line.keepExistingSellingPrice){if(!line.sellingPrice?.trim())throw new Error("Enter a selling price or choose Keep existing selling price.");sellingUnitRatePaisa=rupeesToPaisa(line.sellingPrice);if(sellingUnitRatePaisa<=0n)throw new Error("Selling price must be greater than zero.");}else if(previousSellingRatePaisa<=0n)throw new Error("The first receipt requires a valid selling price.");
    const calculated=inventoryReceiptLine(quantityMilli,purchaseUnitCostPaisa,previousStockMilli,previousAverageCostPaisa);subtotal+=calculated.linePurchaseTotalPaisa;
    receiptLines.push({productId:product._id,productSku:line.productSku,productNameSnapshot:String(product.name),unitSnapshot:String(product.unit),quantityMilli:Long.fromBigInt(quantityMilli),purchaseUnitCostPaisa:Long.fromBigInt(purchaseUnitCostPaisa),sellingUnitRatePaisa:Long.fromBigInt(sellingUnitRatePaisa),linePurchaseTotalPaisa:Long.fromBigInt(calculated.linePurchaseTotalPaisa),previousStockMilli:Long.fromBigInt(previousStockMilli),resultingStockMilli:Long.fromBigInt(calculated.resultingStockMilli),previousAverageCostPaisa:Long.fromBigInt(previousAverageCostPaisa),resultingAverageCostPaisa:Long.fromBigInt(calculated.resultingAverageCostPaisa),previousSellingRatePaisa:Long.fromBigInt(previousSellingRatePaisa)});
    movements.push({transactionNo:number,lineNo:index+1,productId:product._id,productSku:line.productSku,location:"main-shop",type:"inventory-receipt",quantityMilli:Long.fromBigInt(quantityMilli),unitCostPaisa:Long.fromBigInt(purchaseUnitCostPaisa),resultingAverageCostPaisa:Long.fromBigInt(calculated.resultingAverageCostPaisa),businessDate:input.businessDate,date:now,sourceType:"inventory_receipt",sourceTransactionNo:number,status:"posted",createdAt:now,createdBy:actorId});
    if(sellingUnitRatePaisa!==previousSellingRatePaisa){const effectiveFrom=new Date(`${input.businessDate}T00:00:00Z`);await database.collection("product_rate_history").updateMany({productId:product._id,effectiveTo:null,effectiveFrom:{$lt:effectiveFrom}},{$set:{effectiveTo:effectiveFrom,updatedAt:now,updatedBy:actorId}},{session});rateChanges.push({productId:product._id,productSku:line.productSku,previousRatePaisa:Long.fromBigInt(previousSellingRatePaisa),ratePaisa:Long.fromBigInt(sellingUnitRatePaisa),effectiveFrom,effectiveTo:null,businessDate:input.businessDate,source:"inventory_receipt",sourceTransactionNo:number,createdAt:now,createdBy:actorId});}
    const stockUpdate=await database.collection("products").updateOne({_id:product._id,stockMilli:product.stockMilli,averageCostPaisa:product.averageCostPaisa},{$set:{stockMilli:Long.fromBigInt(calculated.resultingStockMilli),averageCostPaisa:Long.fromBigInt(calculated.resultingAverageCostPaisa),retailRatePaisa:Long.fromBigInt(sellingUnitRatePaisa),lastStockReceivedAt:now,updatedAt:now,updatedBy:actorId}},{session});if(!stockUpdate.modifiedCount)throw new Error(`${String(product.name)} stock changed while saving. Please review and try again.`);
    balances.push({sku:line.productSku,stockMilli:calculated.resultingStockMilli.toString(),averageCostPaisa:calculated.resultingAverageCostPaisa.toString(),retailRatePaisa:sellingUnitRatePaisa.toString()});
  }
  let paidAmount=0n;if(input.paymentStatus==="paid")paidAmount=subtotal;else if(input.paymentStatus==="partial")paidAmount=rupeesToPaisa(input.paidAmount??"");
  if(input.paymentStatus!=="unpaid"&&!input.paymentMethod)throw new Error("Select how the inventory payment was made.");if(input.paymentStatus==="partial"&&(paidAmount<=0n||paidAmount>=subtotal))throw new Error("Partial payment must be greater than zero and less than the receipt total.");if(input.paymentStatus==="unpaid"&&input.paymentMethod)throw new Error("Do not select a payment method for an unpaid receipt.");
  const outstanding=subtotal-paidAmount;
  await database.collection("inventory_receipts").insertOne({transactionNo:number,businessDate:input.businessDate,supplierName:input.supplierName||null,supplierReference:input.supplierReference||null,lines:receiptLines,subtotalPaisa:Long.fromBigInt(subtotal),paymentStatus:input.paymentStatus,paymentMethod:input.paymentMethod||null,paidAmountPaisa:Long.fromBigInt(paidAmount),outstandingPaisa:Long.fromBigInt(outstanding),notes:input.notes||null,attachmentKey:input.attachmentKey||null,idempotencyKey:input.idempotencyKey,status:"posted",createdBy:actorId,createdAt:now,updatedBy:actorId,updatedAt:now},{session});
  await database.collection("inventory_movements").insertMany(movements,{session});if(rateChanges.length)await database.collection("product_rate_history").insertMany(rateChanges,{session});
  await database.collection("financial_transactions").insertOne({transactionNo:number,kind:"inventory_purchase",amountPaisa:Long.fromBigInt(subtotal),paidAmountPaisa:Long.fromBigInt(paidAmount),outstandingPaisa:Long.fromBigInt(outstanding),businessDate:input.businessDate,status:"posted",createdAt:now,createdBy:actorId},{session});
  if(paidAmount>0n)await database.collection("cashbook_entries").insertOne({transactionNo:number,lineNo:1,businessDate:input.businessDate,account:input.paymentMethod,direction:"out",amountPaisa:Long.fromBigInt(paidAmount),description:`Inventory purchase ${number}`,status:"posted",sourceType:"inventory_receipt",createdAt:now,createdBy:actorId},{session});
  await database.collection("audit_logs").insertOne({actorId,action:"post",entity:"inventory_receipt",entityId:number,metadata:{subtotalPaisa:subtotal.toString(),paidAmountPaisa:paidAmount.toString()},createdAt:now},{session});const result={transactionNo:number,subtotalPaisa:subtotal.toString(),paidAmountPaisa:paidAmount.toString(),balances};await database.collection("idempotency_records").insertOne({key:input.idempotencyKey,operation:"inventory_receipt",result,createdAt:now},{session});return result;
}).catch(error=>{if(duplicate(error))throw new Error("This inventory receipt was already saved. Refresh to see it in history.");throw error})}

export async function reverseInventoryReceipt(transactionNumber:string,reason:string,actorId:string){
  if(reason.trim().length<5)throw new Error("Enter a clear reversal reason.");
  return transaction(async(database,session)=>{
    const receipt=await database.collection("inventory_receipts").findOne({transactionNo:transactionNumber,status:"posted"},{session});if(!receipt)throw new Error("This receipt is missing or already reversed.");
    const now=new Date(),reversalNo=transactionNo("REV-INV"),movements:Document[]=[];
    for(const[index,line]of (receipt.lines as Document[]).entries()){
      const product=await database.collection("products").findOne({_id:line.productId},{session}),currentStock=integerToBigInt(product?.stockMilli),resultingStock=integerToBigInt(line.resultingStockMilli);
      if(line.productSku==="EGG-001"){
        if(!product||currentStock!==resultingStock||integerToBigInt(product.pieceSellingRatePaisa)!==integerToBigInt(line.pieceSellingRatePaisa)||integerToBigInt(product.traySellingRatePaisa)!==integerToBigInt(line.traySellingRatePaisa))throw new Error("Egg stock or selling prices changed after this receipt. It cannot be reversed safely.");
        await database.collection("products").updateOne({_id:product._id,stockMilli:product.stockMilli},{$set:{stockMilli:line.previousStockMilli,averageCostPaisa:line.previousAverageCostPaisa,retailRatePaisa:line.previousPieceSellingRatePaisa,pieceSellingRatePaisa:line.previousPieceSellingRatePaisa,traySellingRatePaisa:line.previousTraySellingRatePaisa,updatedAt:now,updatedBy:actorId}},{session});
        movements.push({transactionNo:reversalNo,lineNo:index+1,productId:line.productId,productSku:"EGG-001",location:"main-shop",type:"inventory-receipt-reversal",enteredQuantity:line.enteredQuantity,enteredUnit:line.enteredUnit,piecesPerTray:line.piecesPerTraySnapshot,normalizedPieces:Long.fromBigInt(-integerToBigInt(line.normalizedPieceQuantity)),quantityMilli:Long.fromBigInt(-integerToBigInt(line.quantityMilli)),unitCostPaisa:line.purchaseUnitCostPaisa,businessDate:receipt.businessDate,date:now,sourceType:"inventory_receipt_reversal",sourceTransactionNo:transactionNumber,reversesTransactionNo:transactionNumber,status:"posted",createdAt:now,createdBy:actorId});continue;
      }
      if(!product||currentStock!==resultingStock||integerToBigInt(product.retailRatePaisa)!==integerToBigInt(line.sellingUnitRatePaisa))throw new Error(`${String(line.productNameSnapshot)} stock or selling price changed after this receipt. It cannot be reversed safely.`);
      await database.collection("products").updateOne({_id:product._id,stockMilli:product.stockMilli,retailRatePaisa:product.retailRatePaisa},{$set:{stockMilli:line.previousStockMilli,averageCostPaisa:line.previousAverageCostPaisa,retailRatePaisa:line.previousSellingRatePaisa,updatedAt:now,updatedBy:actorId}},{session});
      if(integerToBigInt(line.sellingUnitRatePaisa)!==integerToBigInt(line.previousSellingRatePaisa)){await database.collection("product_rate_history").updateMany({productId:line.productId,effectiveTo:null},{$set:{effectiveTo:now,updatedAt:now,updatedBy:actorId}},{session});await database.collection("product_rate_history").insertOne({productId:line.productId,productSku:line.productSku,previousRatePaisa:line.sellingUnitRatePaisa,ratePaisa:line.previousSellingRatePaisa,effectiveFrom:now,effectiveTo:null,businessDate:receipt.businessDate,source:"inventory_receipt_reversal",sourceTransactionNo:reversalNo,createdAt:now,createdBy:actorId},{session});}
      movements.push({transactionNo:reversalNo,lineNo:index+1,productId:line.productId,productSku:line.productSku,location:"main-shop",type:"inventory-receipt-reversal",quantityMilli:Long.fromBigInt(-integerToBigInt(line.quantityMilli)),unitCostPaisa:line.purchaseUnitCostPaisa,businessDate:receipt.businessDate,date:now,sourceType:"inventory_receipt_reversal",sourceTransactionNo:transactionNumber,reversesTransactionNo:transactionNumber,status:"posted",createdAt:now,createdBy:actorId});
    }
    await database.collection("inventory_movements").insertMany(movements,{session});const paid=integerToBigInt(receipt.paidAmountPaisa),subtotal=integerToBigInt(receipt.subtotalPaisa);
    if(paid>0n)await database.collection("cashbook_entries").insertOne({transactionNo:reversalNo,lineNo:1,businessDate:receipt.businessDate,account:receipt.paymentMethod,direction:"in",amountPaisa:Long.fromBigInt(paid),description:`Reversal of ${transactionNumber}`,status:"posted",sourceType:"inventory_receipt_reversal",createdAt:now,createdBy:actorId},{session});
    await database.collection("financial_transactions").insertOne({transactionNo:reversalNo,kind:"inventory_purchase_reversal",amountPaisa:Long.fromBigInt(-subtotal),businessDate:receipt.businessDate,reversesTransactionNo:transactionNumber,status:"posted",createdAt:now,createdBy:actorId},{session});
    await database.collection("inventory_receipts").updateOne({_id:receipt._id,status:"posted"},{$set:{status:"reversed",reversedBy:actorId,reversedAt:now,reversalReason:reason.trim(),reversalTransactionNo:reversalNo,updatedBy:actorId,updatedAt:now}},{session});
    await database.collection("audit_logs").insertOne({actorId,action:"reverse",entity:"inventory_receipt",entityId:receipt._id,metadata:{transactionNumber,reversalNo,reason:reason.trim()},createdAt:now},{session});return{reversalNo};
  });
}
