"use server";
import { revalidatePath } from "next/cache";
import { requireSession } from "@/lib/auth";
import { inventoryReceiptSchema, postInventoryReceipt, reverseInventoryReceipt } from "@/lib/services/inventory-receipt";
import { adjustMilkStock, stockAdjustmentSchema } from "@/lib/services/stock-adjustment";
export type InventoryState={error?:string;result?:{transactionNo:string;subtotalPaisa:string;paidAmountPaisa:string;balances:Array<{sku:string;stockMilli:string;averageCostPaisa:string;retailRatePaisa:string}>}};
export async function addInventory(_:InventoryState,formData:FormData):Promise<InventoryState>{const actor=await requireSession(["owner","manager","accountant"]);let payload:unknown;try{payload=JSON.parse(String(formData.get("payload")))}catch{return{error:"The inventory receipt is invalid."}}const parsed=inventoryReceiptSchema.safeParse(payload);if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Check the inventory details."};try{const result=await postInventoryReceipt(parsed.data,actor.userId);revalidatePath("/inventory");revalidatePath("/deliveries");revalidatePath("/dashboard");return{result}}catch(error){return{error:error instanceof Error?error.message:"Inventory could not be added."}}}
export type ReversalState={error?:string;success?:string};
export async function reverseReceipt(_:ReversalState,formData:FormData):Promise<ReversalState>{const actor=await requireSession(["owner"]);const transactionNumber=String(formData.get("transactionNo")??""),reason=String(formData.get("reason")??"");try{const result=await reverseInventoryReceipt(transactionNumber,reason,actor.userId);revalidatePath("/inventory");revalidatePath("/deliveries");return{success:`Reversed as ${result.reversalNo}`}}catch(error){return{error:error instanceof Error?error.message:"Receipt could not be reversed."}}}
export async function adjustMilk(_:ReversalState,formData:FormData):Promise<ReversalState>{const actor=await requireSession(["owner"]),parsed=stockAdjustmentSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Check the milk adjustment."};try{const result=await adjustMilkStock(parsed.data,actor.userId);revalidatePath("/inventory");revalidatePath("/dashboard");return{success:`Adjusted as ${String(result?.transactionNo)}`}}catch(error){return{error:error instanceof Error?error.message:"Milk stock could not be adjusted."}}}
