import Link from "next/link";
import { db } from "@/lib/db";
import { normalizePakistanPhone } from "@/lib/customer-statement";
import { formatMilli, formatPKR, integerToBigInt } from "@/lib/money";
import { karachiBusinessDate } from "@/lib/queries";
import { CustomerForm, PaymentForm } from "./customer-forms";
export const dynamic="force-dynamic";

export default async function Page(){
  const database=await db(),businessDate=karachiBusinessDate(),month=businessDate.slice(0,7),start=`${month}-01`,[year,value]=month.split("-").map(Number),next=new Date(Date.UTC(year,value,1)).toISOString().slice(0,10);
  const rows=await database.collection("customers").aggregate([{$sort:{deliverySequence:1,name:1}},{$lookup:{from:"party_ledger_entries",let:{id:"$_id"},pipeline:[{$match:{$expr:{$and:[{$eq:["$partyId","$$id"]},{$eq:["$partyType","customer"]},{$eq:["$status","posted"]}]}}},{$group:{_id:null,debit:{$sum:"$debitPaisa"},credit:{$sum:"$creditPaisa"},monthDebit:{$sum:{$cond:[{$and:[{$gte:["$businessDate",start]},{$lt:["$businessDate",next]}]},"$debitPaisa",0]}},monthCredit:{$sum:{$cond:[{$and:[{$gte:["$businessDate",start]},{$lt:["$businessDate",next]}]},"$creditPaisa",0]}}}}],as:"ledger"}},{$lookup:{from:"customer_deliveries",let:{id:"$_id"},pipeline:[{$match:{$expr:{$and:[{$eq:["$customerId","$$id"]},{$eq:["$status","posted"]},{$gte:["$businessDate",start]},{$lt:["$businessDate",next]}]}}},{$group:{_id:null,milk:{$sum:"$milkQuantityMilli"},milkCharges:{$sum:"$milkAmountPaisa"},otherCharges:{$sum:"$otherAmountPaisa"}}}],as:"monthDeliveries"}}]).toArray();
  return <div className="content"><div className="customer-heading"><div><div className="title">Customers</div><div className="subtitle">Household deliveries, monthly billing and money to receive.</div></div><Link className="button" href="/deliveries">Open Daily Deliveries</Link></div><CustomerForm/><div className="card table-card table-scroll">{rows.length?<table className="table"><thead><tr><th>Code</th><th>Customer</th><th>This month</th><th>Payments</th><th>Money to receive</th><th>Actions</th></tr></thead><tbody>{rows.map(row=>{const ledger=row.ledger?.[0],delivery=row.monthDeliveries?.[0],balance=integerToBigInt(ledger?.debit)-integerToBigInt(ledger?.credit),milk=integerToBigInt(delivery?.milk),milkCharges=integerToBigInt(delivery?.milkCharges),otherCharges=integerToBigInt(delivery?.otherCharges),payments=integerToBigInt(ledger?.monthCredit),previous=balance-(integerToBigInt(ledger?.monthDebit)-payments);const message=encodeURIComponent(`Assalam-o-Alaikum ${row.name}. During ${month}, you received ${formatMilli(milk)} liters of milk. Milk charges: ${formatPKR(milkCharges)}. Other product charges: ${formatPKR(otherCharges)}. Previous balance: ${formatPKR(previous)}. Payments received: ${formatPKR(payments)}. Your remaining DairyFlow balance is ${formatPKR(balance)}.`);return <tr key={row._id.toString()}><td><b>{row.code}</b></td><td>{row.name}<div className="subtitle">{row.address}</div></td><td>{formatMilli(milk)} L · {formatPKR(milkCharges+otherCharges)}</td><td>{formatPKR(payments)}</td><td><b>{formatPKR(balance)}</b></td><td><div className="toolbar"><PaymentForm id={row._id.toString()} businessDate={businessDate}/><Link className="button secondary" href={`/customers/${row._id}?month=${month}`}>Statement</Link><a className="button secondary" href={`https://wa.me/${normalizePakistanPhone(String(row.whatsapp||row.phone))}?text=${message}`} target="_blank" rel="noreferrer">WhatsApp</a></div></td></tr>})}</tbody></table>:<div className="empty-state"><b>No customers yet</b><span>Add the first household customer to start daily deliveries.</span></div>}</div></div>;
}
